### ISSUE TITLE
Can not restart app

### ISSUE THREAD

**Issue by matedon** [Sandip124/BatteryNotifier#72]
I am started to use this app now. Version 2.2.4.
Closed the app with menu exit.
After that I can not start it again with Desktop shortcut.
It is starting again only when I reboot the machine.
Windows 10.

**Comment by Sandip124** [comment]
@matedon firstly thanks for the bug, the issue was due to the app actually resides in the taskbar so the new instance is not showed, and not i have used another technique to solve this. in this => https://github.com/Sandip124/BatteryNotifier/releases/tag/v3.0.0 release i have fixed that issue too. once again thanks for your patience. now give it a try to the v3.0.0
